
library(devtools)
# create_package(here::here("Rpackage"))

# use_r("get_odata_catalogue")
# use_r("get_odata")

load_all()
check()
use_mit_license()
document()
check()
install()
library(Rpackage)
use_testthat()
use_test("get_odata_catalogue")
use_package("tidyr")
use_package("httr")
use_package("jsonlite")
use_package("stringr")
use_package("dplyr")
